// Decipher Technology Studios, LLC (“Decipher”) owns all right, title to and interest in the Grey Matter software (the “Software”).
// Use of and access to the Software is governed by the Decipher Technology Studios End User License Agreement (the “EULA”).

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/bcmendoza/gm-operator/apis/install/v1"
	"github.com/bcmendoza/gm-operator/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type InstallV1Interface interface {
	RESTClient() rest.Interface
	OperatorsGetter
}

// InstallV1Client is used to interact with features provided by the install.greymatter.io group.
type InstallV1Client struct {
	restClient rest.Interface
}

func (c *InstallV1Client) Operators(namespace string) OperatorInterface {
	return newOperators(c, namespace)
}

// NewForConfig creates a new InstallV1Client for the given config.
func NewForConfig(c *rest.Config) (*InstallV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &InstallV1Client{client}, nil
}

// NewForConfigOrDie creates a new InstallV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *InstallV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new InstallV1Client for the given RESTClient.
func New(c rest.Interface) *InstallV1Client {
	return &InstallV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *InstallV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
