apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: operator
        args:
        - "--configPath=config/bootstrap_config.yaml"
        volumeMounts:
        - name: operator-config
          mountPath: /app/config/bootstrap_config.yaml
          subPath: bootstrap_config.yaml
      volumes:
      - name: operator-config
        configMap:
          name: operator-config
