// Decipher Technology Studios, LLC (“Decipher”) owns all right, title to and interest in the Grey Matter software (the “Software”).
// Use of and access to the Software is governed by the Decipher Technology Studios End User License Agreement (the “EULA”).

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/bcmendoza/gm-operator/client/clientset/versioned/typed/install/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeInstallV1 struct {
	*testing.Fake
}

func (c *FakeInstallV1) Operators(namespace string) v1.OperatorInterface {
	return &FakeOperators{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeInstallV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
