// Decipher Technology Studios, LLC (“Decipher”) owns all right, title to and interest in the Grey Matter software (the “Software”).
// Use of and access to the Software is governed by the Decipher Technology Studios End User License Agreement (the “EULA”).

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	installv1 "github.com/bcmendoza/gm-operator/apis/install/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOperators implements OperatorInterface
type FakeOperators struct {
	Fake *FakeInstallV1
	ns   string
}

var operatorsResource = schema.GroupVersionResource{Group: "install.greymatter.io", Version: "v1", Resource: "operators"}

var operatorsKind = schema.GroupVersionKind{Group: "install.greymatter.io", Version: "v1", Kind: "Operator"}

// Get takes name of the operator, and returns the corresponding operator object, and an error if there is any.
func (c *FakeOperators) Get(ctx context.Context, name string, options v1.GetOptions) (result *installv1.Operator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(operatorsResource, c.ns, name), &installv1.Operator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*installv1.Operator), err
}

// List takes label and field selectors, and returns the list of Operators that match those selectors.
func (c *FakeOperators) List(ctx context.Context, opts v1.ListOptions) (result *installv1.OperatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(operatorsResource, operatorsKind, c.ns, opts), &installv1.OperatorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &installv1.OperatorList{ListMeta: obj.(*installv1.OperatorList).ListMeta}
	for _, item := range obj.(*installv1.OperatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested operators.
func (c *FakeOperators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(operatorsResource, c.ns, opts))

}

// Create takes the representation of a operator and creates it.  Returns the server's representation of the operator, and an error, if there is any.
func (c *FakeOperators) Create(ctx context.Context, operator *installv1.Operator, opts v1.CreateOptions) (result *installv1.Operator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(operatorsResource, c.ns, operator), &installv1.Operator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*installv1.Operator), err
}

// Update takes the representation of a operator and updates it. Returns the server's representation of the operator, and an error, if there is any.
func (c *FakeOperators) Update(ctx context.Context, operator *installv1.Operator, opts v1.UpdateOptions) (result *installv1.Operator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(operatorsResource, c.ns, operator), &installv1.Operator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*installv1.Operator), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOperators) UpdateStatus(ctx context.Context, operator *installv1.Operator, opts v1.UpdateOptions) (*installv1.Operator, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(operatorsResource, "status", c.ns, operator), &installv1.Operator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*installv1.Operator), err
}

// Delete takes name of the operator and deletes it. Returns an error if one occurs.
func (c *FakeOperators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(operatorsResource, c.ns, name), &installv1.Operator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOperators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(operatorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &installv1.OperatorList{})
	return err
}

// Patch applies the patch and returns the patched operator.
func (c *FakeOperators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *installv1.Operator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(operatorsResource, c.ns, name, pt, data, subresources...), &installv1.Operator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*installv1.Operator), err
}
