apiVersion: greymatter.io/v1alpha1
kind: OperatorConfig
webhook:
  port: 9443
metrics:
  bindAddress: 127.0.0.1:8080
leaderElection:
  leaderElect: false
imagePullSecretName: docker.secret
redis:
  # example: "redis://<user>:<pass>@localhost:6379/<db>"
  url: ""
  # this secret should have keys: ca, server_cert, server_key
  # if this is empty tls is not enabled 
  certificateSecretName: ""
