FROM docker.io/cfssl/cfssl:latest as cfssl

WORKDIR /tmp

EXPOSE 8888
USER 1000

ENTRYPOINT ["/bin/bash"]

CMD ["-c", "cfssl gencert -initca -config=cfssl/ca-config.json cfssl/ca-csr.json | cfssljson -bare ca && cfssl serve -ca=ca.pem -ca-key=ca-key.pem"]
