apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiZG9ja2VyLmdyZXltYXR0ZXIuaW8iOiB7ImF1dGgiOiAiWTI5c1pXMWhiaTV0WTJaaGNteGhibVJBWjNKbGVXMWhkSFJsY2k1cGJ6cDBkWEowYkdVbGQyVnNiR0psYVc1blJrOVNRMFY0T0RZPSJ9fX0=
kind: Secret
metadata:
  name: gm-docker-secret
  namespace: gm-operator
type: kubernetes.io/dockerconfigjson
