apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gm-operator
  namespace: gm-operator
spec:
  template:
    spec:
      containers:
      - name: operator
        image: "docker.greymatter.io/internal/gm-operator:local_refactored"
