steps:
  - label: "run unit tests"
    agents:
      container_image: ubuntu-2110-ci
    commands: 
      - ./scripts/cibuild bootstrap
      - ./scripts/cibuild test
  - wait
  - label: ":shipit: build and release"
    agents:
      container_image: ubuntu-2110-ci
    commands:
      - ./scripts/cibuild bootstrap
      - ./scripts/cibuild build
      - ./scripts/cibuild export_container "${BUILDKITE_PIPELINE_SLUG}_${BUILDKITE_BUILD_NUMBER}.tar" "docker.greymatter.io/development/gm-operator:latest"
      - ./scripts/cibuild release
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
  - wait
  - label: "run integration tests"
    commands:
      - ./scripts/cibuild generate_integration_tests