apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: control
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: control
subjects:
- kind: ServiceAccount
  name: control
  namespace: gm-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: control
  namespace: gm-operator
automountServiceAccountToken: false
