# permissions for end users to edit installvaluesconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installvaluesconfig-editor-role
rules:
- apiGroups:
  - greymatter.io
  resources:
  - installvaluesconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
