# permissions for end users to view installvaluesconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installvaluesconfig-viewer-role
rules:
- apiGroups:
  - greymatter.io
  resources:
  - installvaluesconfigs
  verbs:
  - get
  - list
  - watch
