# permissions for end users to edit systemvaluesconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: systemvaluesconfig-editor-role
rules:
- apiGroups:
  - greymatter.io
  resources:
  - systemvaluesconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
