apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci
  namespace: gm-operator-test3
  labels:
    app: fibonacci
    greymatter.io/exclude-from-mesh: "true"
spec:
  selector:
    matchLabels:
      app: fibonacci
  template:
    metadata:
      labels:
        app: fibonacci
    spec:
      containers:
      - image: docker.greymatter.io/internal/fibonacci:latest
        imagePullPolicy: Always
        name: fibonacci
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      imagePullSecrets:
        - name: gm-docker-secret
