apiVersion: greymatter.io/v1alpha1
kind: Mesh
metadata:
  name: mesh-sample
spec:
  release_version: '1.7'
  zone: default-zone
  install_namespace: default
  watch_namespaces:
  - gm-operator-watched
---
apiVersion: v1
kind: Namespace
metadata:
  name: gm-operator-watched
