apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: gm-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Mesh defines a Grey Matter mesh's desired state and describes its
        observed state.
      displayName: Mesh
      kind: Mesh
      name: meshes.greymatter.io
      version: v1alpha1
  description: Manage Grey Matter mesh installation and configuration in your Kubernetes
    cluster.
  displayName: Grey Matter Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - service mesh
  links:
  - name: Grey Matter Operator
    url: https://github.com/greymatter-io/operator
  maintainers:
  - email: brian.mendoza@greymatter.io
    name: Brian Mendoza
  - email: kyle.gallagher@greymatter.io
    name: Kyle Gallagher
  maturity: alpha
  provider:
    name: Decipher Technology Studios
    url: https://greymatter.io
  version: 0.0.0
