apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Mesh is the Schema for the meshes API
      displayName: Mesh
      kind: Mesh
      name: meshes.greymatter.io
      version: v1alpha1
  description: TODO
  displayName: Grey Matter Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - service mesh
  links:
  - name: Operator
    url: https://operator.domain
  maintainers:
  - email: info@greymatter.io
    name: Info
  maturity: alpha
  provider:
    name: Decipher Technology Studios
    url: https://greymatter.io
  version: 0.0.0
