apiVersion: v1
kind: ConfigMap
metadata:
  name: gm-cfssl-config
  namespace: gm-operator
data:
  ca-config.json: |
    {
      "signing": {
        "default": {
          "expiry": "8760h"
        },
        "profiles": {
          "server": {
            "usages": ["signing", "key encipherment", "server auth", "client auth"],
            "expiry": "8760h"
          }
        }
      }
    }
  ca-csr.json: |
    {
      "CN": "greymatter.io",
      "hosts": [
        "greymatter.io",
        "www.greymatter.io"
      ],
      "key": {
        "algo": "rsa",
        "size": 2048
      },
      "names": [
        {
          "C": "US",
          "ST": "VA",
          "O": "Grey Matter"
        }
      ]
    }
