bases:
- ../default

resources:
# Add an opaque secret which will be populated by the operator with signed certs from cfssl
- webhook_secret.yaml

patchesStrategicMerge:
# Patch our deployment so the right Docker image is used
# Note: These are not meant to be separate images; just used separately in dev
- manager_image_patch.yaml
# Patch the bootstrap config since we need to keep cert generation turned on
- bootstrap_config_patch.yaml
