apiVersion: apps/v1
kind: Deployment
metadata:
  name: gm-controller-manager
  namespace: gm-operator
spec:
  template:
    spec:
      containers:
      - name: manager
        image: docker.greymatter.io/internal/gm-operator:latest-kops
