# The webhook cert secret is meant to be initialized as empty, and will be populated by the operator at startup
# when the operator instructs its embedded CFSSL server to sign and issue the contents of tls.crt and tls.key.
apiVersion: v1
kind: Secret
metadata:
  name: gm-controller-manager-service-cert
  namespace: gm-operator
data:
  tls.crt: ""
  tls.key: ""
