apiVersion: greymatter.io/v1alpha1
kind: InstallationConfig
metadata:
  name: installationconfig-sample
proxy: {}
edge: {}
control: {}
controlApi: {}
catalog: {}
dashboard: {}
jwtSecurity: {}
redis: {}
prometheus: {}
