apiVersion: greymatter.io/v1alpha1
kind: InstallationConfig
metadata:
  name: fixture

proxy:
  image: docker.greymatter.io/release/gm-proxy:1.6.4
  ports:
    metrics:
      protocol: TCP
      containerPort: 8081
  envs:
    ENVOY_ADMIN_LOG_PATH: /dev/stdout
    PROXY_DYNAMIC: "true"
    XDS_CLUSTER: ""
    XDS_ZONE: ""
    XDS_HOST: ""
    XDS_PORT: "50000"
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

edge:
  envs:
    XDS_CLUSTER: edge
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

control:
  image: docker.greymatter.io/release/gm-control:1.6.4
  ports:
    xDS:
      protocol: TCP
      containerPort: 50000
  envs:
    GM_CONTROL_API_ZONE_NAME: ""
    GM_CONTROL_CMD: kubernetes
    GM_CONTROL_KUBERNETES_NAMESPACES: ""
    GM_CONTROL_KUBERNETES_CLUSTER_LABEL: greymatter.io/cluster
    GM_CONTROL_KUBERNETES_PORT_NAME: proxy
    GM_CONTROL_API_HOST: localhost:5555
    GM_CONTROL_API_INSECURE: "true"
    GM_CONTROL_API_SSL: "false"

controlApi:
  image: docker.greymatter.io/release/gm-control-api:1.6.4
  labels:
    greymatter.io/cluster: control-api
    greymatter.io/service-version: "1.6"
  ports:
    api:
      protocol: TCP
      containerPort: 5555
  envs:
    GM_CONTROL_API_ADDRESS: "0.0.0.0:5555"
    GM_CONTROL_API_DISABLE_VERSION_CHECK: "false"
    GM_CONTROL_API_ZONE_KEY: ""
    GM_CONTROL_API_ZONE_NAME: ""
    GM_CONTROL_API_PERSISTER_TYPE: redis
    GM_CONTROL_API_REDIS_HOST: ""
    GM_CONTROL_API_REDIS_PORT: ""
    GM_CONTROL_API_REDIS_PASS: ""
    GM_CONTROL_API_REDIS_DB: ""
    GM_CONTROL_API_REDIS_MAX_RETRIES: "50"
    GM_CONTROL_API_REDIS_RETRY_DELAY: "5s"

catalog:
  image: docker.greymatter.io/release/gm-control-api:2.0.0
  labels:
    greymatter.io/cluster: catalog
    greymatter.io/service-version: "2.0"
  ports:
    api:
      protocol: TCP
      containerPort: 8080
  envs:
    CONFIG_SOURCE: redis
    REDIS_HOST: ""
    REDIS_PORT: ""
    REDIS_PASS: ""
    REDIS_DB: ""
    REDIS_MAX_RETRIES: "50"
    REDIS_RETRY_DELAY: "5s"

dashboard:
  image: docker.greymatter.io/release/gm-dashboard:5.0.0
  labels:
    greymatter.io/cluster: dashboard
    greymatter.io/service-version: "5.0"
  ports:
    app:
      protocol: TCP
      containerPort: 1337
  envs:
    REQUEST_TIMEOUT: "15000"
    BASE_URL: "/services/dashboard/5.0/"
    FABRIC_SERVER: "/services/catalog/2.0/"
    CONFIG_SERVER: "/services/control-api/1.6/v1.0"
    PROMETHEUS_SERVER: "/services/prometheus/latest/api/v1/"
    USE_PROMETHEUS: "true"
    DISABLE_PROMETHEUS_ROUTES_UI: "false"
    ENABLE_INLINE_DOCS: "true"

jwtSecurity:
  image: docker.greymatter.io/release/gm-jwt-security:1.3.0
  labels:
    greymatter.io/cluster: jwt-security
    greymatter.io/service-version: "1.3"
  ports:
    api:
      protocol: TCP
      containerPort: 3000
  envs:
    HTTP_PORT: "3000"
    REDIS_HOST: ""
    REDIS_PORT: ""
    REDIS_PASS: ""
    REDIS_DB: ""
    JWT_API_KEY: MTIzCg==
    PRIVATE_KEY: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1JSGNBZ0VCQkVJQkhRY01yVUh5ZEFFelNnOU1vQWxneFF1a3lqQTROL2laa21ETVIvdFRkVmg3U3hNYk8xVE4KeXdzRkJDdTYvZEZXTE5rUDJGd1FFQmtqREpRZU9mc3hKZWlnQndZRks0RUVBQ09oZ1lrRGdZWUFCQUJEWklJeAp6a082cWpkWmF6ZG1xWFg1dnRFcWtodzlkcVREeTN6d0JkcXBRUmljWDRlS2lZUUQyTTJkVFJtWk0yZE9FRHh1Clhja0hzcVMxZDNtWHBpcDh2UUZHTWJCM1hRVm9DZWN0SUlLMkczRUlwWmhGZFNGdG1sa2t5U1N4angzcS9UcloKaVlRTjhJakpPbUNueUdXZ1VWUkdERURiNWlZdkZXc3dpSkljSWYyOGVRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo
  volumes:
    jwt-users:
      configMap:
        name: jwt-users
        defaultMode: 420
  volumeMounts:
    jwt-users:
      mountPath: /gm-jwt-security/etc
