#!/bin/bash

set -e

for dependency in go greymatter operator-sdk kustomize cue staticcheck
do
    if ! which $dependency &> /dev/null; then
        echo "$dependency is missing from your \$PATH"
        exit 1
    elif [ "$dependency" == "go" ]; then
        go mod tidy
        go mod vendor
    elif [ "$dependency" == "cue" ]; then
        (cd ./pkg/cuedata/cue.mod; cue get go k8s.io/api/...)
    fi
done
