#!/bin/bash

# Builds a local, native build by default
# Can build a container build if passed appropriate args

set -euf -o pipefail

if [ $# -eq 0 ]
then
  make build
else
  case $1 in 
  docker)
    make docker-build VERSION=latest
    ;;
  *) 
    echo "invalid argument $1"
    exit 1
    ;;
  esac
fi
