#!/bin/bash

set -euf -o pipefail

cli_deploy() {
  greymatter k8s operator | kubectl apply -f -
}

# Openshift

oc_push() {
  push_docker
}

oc_deploy() {
  push_docker

  oc create secret docker-registry gm-docker-secret \
    --docker-server=docker.greymatter.io \
    --docker-username=$GREYMATTER_REGISTRY_USERNAME \
    --docker-password=$GREYMATTER_REGISTRY_PASSWORD \
    --docker-email=$GREYMATTER_REGISTRY_USERNAME \
    -n gm-operator

  make pkgmanifests VERSION=0.0.1 CHANNEL=alpha IS_CHANNEL_DEFAULT=1 IMG=docker.greymatter.io/internal/gm-operator:latest
  operator-sdk run packagemanifests -n gm-operator --version 0.0.1
  rm -rf ./packagemanifests
}

oc_cleanup() {
  operator-sdk cleanup -n gm-operator gm-operator
  oc delete pvc gm-redis-append-dir-gm-redis-0
}

oc_upgrade() {
  oc_cleanup
  oc_deploy
}

oc_logs() {
  oc logs -n gm-operator $(oc get pod -n gm-operator -o json | jq -c '.items[0] | select(.metadata.name | contains("operator")).metadata.name' | xargs) -c operator -f
}

# Kubernetes

k8s_push() {
  push_docker
}

k8s_deploy() {
  push_docker
  k_deploy kops
}

k8s_cleanup() {
  kubectl delete -k config/context/kubernetes-dev
  kubectl delete pvc gm-redis-append-dir-gm-redis-0 -n default
}

k8s_upgrade() {
  push_docker
  kubectl delete pod -n gm-operator $(kubectl get pod -n gm-operator -o json | jq -c '.items[] | select(.metadata.name | contains("operator")).metadata.name' | xargs)
}

k8s_logs() {
  kubectl logs -n gm-operator $(kubectl get pod -n gm-operator -o json | jq -c '.items[] | select(.metadata.name | contains("operator")).metadata.name' | xargs) -c operator -f
}

# K3D (local development)

k3d_push() {
  ./scripts/build container
  k3d image import -c gm-operator docker.greymatter.io/internal/gm-operator:latest
}

k3d_deploy() {
  k3d_push
  k_deploy k3d
}

k3d_cleanup() {
  kubectl delete -k config/context/kubernetes-dev
  kubectl delete pvc gm-redis-append-dir-gm-redis-0 -n default
}

k3d_upgrade() {
  ./scripts/build container
  k3d image import -c gm-operator docker.greymatter.io/internal/gm-operator:latest
  kubectl delete pod -n gm-operator $(kubectl get pod -n gm-operator -o json | jq -c '.items[] | select(.metadata.name | contains("operator")).metadata.name' | xargs)
}

k3d_logs() {
  kubectl logs -n gm-operator $(kubectl get pod -n gm-operator -o json | jq -c '.items[] | select(.metadata.name | contains("operator")).metadata.name' | xargs) -c operator -f
}

# Shared

push_docker() {
  ./scripts/build container
  docker push docker.greymatter.io/internal/gm-operator:latest
}

k_deploy() {
  kubectl apply -k config/context/kubernetes-dev

  kubectl create secret docker-registry gm-docker-secret \
  --docker-server=docker.greymatter.io \
  --docker-username=$GREYMATTER_REGISTRY_USERNAME \
  --docker-password=$GREYMATTER_REGISTRY_PASSWORD \
  --docker-email=$GREYMATTER_REGISTRY_USERNAME \
  -n gm-operator
}

choose() {
  case $1 in
    k3d) k3d_$2 ;;
    k8s) k8s_$2 ;;
    oc)  oc_$2 ;;
    cli) cli_$2 ;;
    *)
      echo "invalid argument $1: expected match with k3d, k8s, or oc."
      exit 1
      ;;
  esac
}

if [ $# -lt 2 ]; then
  echo "dev: expected at least 2 arguments"
  exit 1
fi

case $1 in
  push)     choose $2 push;    ;;
  deploy)   choose $2 deploy;  ;;
  cleanup)  choose $2 cleanup; ;;
  upgrade)  choose $2 upgrade; ;;
  logs)     choose $2 logs;    ;;
  *)
    echo "invalid argument $1"
    exit 1
    ;;
esac
