#!/bin/bash

set -euf -o pipefail

format_packagemanifests() {
	sed -i'.original' -e "s|development/gm-operator:$1|internal/gm-operator:latest|" ./packagemanifests/$1/gm-operator.clusterserviceversion.yaml
	rm ./packagemanifests/$1/gm-operator.clusterserviceversion.yaml.original
}

if [ $# -lt 1 ]
then
  echo "dev: missing argument"
  exit 1
fi

case $1 in
  push)
    make docker-build IMG=docker.greymatter.io/internal/gm-operator:latest
    make docker-push IMG=docker.greymatter.io/internal/gm-operator:latest
    oc delete pod -n gm-operator -l control-plane=controller-manager
    ;;
  run)
    make packagemanifests VERSION=0.0.1 CHANNEL=alpha IS_CHANNEL_DEFAULT=1
    format_packagemanifests 0.0.1
    operator-sdk run packagemanifests -n gm-operator --version 0.0.1
    rm -rf ./packagemanifests
    ;;
  upgrade)
    ./scripts/dev cleanup
    echo "waiting for cleanup process"
    sleep 10
    ./scripts/dev run
    ;;
  cleanup)
    operator-sdk cleanup -n gm-operator gm-operator
    ;;
  *)
    echo "invalid argument $1"
    exit 1
    ;;
esac
