// Decipher Technology Studios, LLC (“Decipher”) owns all right, title to and interest in the Grey Matter software (the “Software”).
// Use of and access to the Software is governed by the Decipher Technology Studios End User License Agreement (the “EULA”).

// Code generated by lister-gen. DO NOT EDIT.

package v1

// MeshListerExpansion allows custom methods to be added to
// MeshLister.
type MeshListerExpansion interface{}

// MeshNamespaceListerExpansion allows custom methods to be added to
// MeshNamespaceLister.
type MeshNamespaceListerExpansion interface{}
